wandb_version: 1

K:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
activation_function:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: expert
device:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 0.1
embed_dim:
  desc: null
  value: 128
env:
  desc: null
  value: halfcheetah
eval_iters:
  desc: null
  value: 5,10,15
learning_rate:
  desc: null
  value: 0.0001
log_to_wandb:
  desc: null
  value: true
max_iters:
  desc: null
  value: 15
mode:
  desc: null
  value: normal
model_name:
  desc: null
  value: ''
n_head:
  desc: null
  value: 1
n_layer:
  desc: null
  value: 3
num_eval_episodes:
  desc: null
  value: 100
num_steps_per_iter:
  desc: null
  value: 10000
save_iters:
  desc: null
  value: 5,10,11,12,13,14,15
save_path:
  desc: null
  value: ./saved_models
warmup_steps:
  desc: null
  value: 10000
weight_decay:
  desc: null
  value: 0.0001
